### ISSUE TITLE
Possibility to add templates to the framework

### ISSUE THREAD

**Issue by carlosdaniel26** [FabioAugustoRodrigues/iMono#1]
I was taking a look at the code and apparently a template system is missing, I think using templates can be more practical than changing the content using javascript.

have any idea of ​​creating it in the future? If so, I'm interested in contributing.

**Comment by FabioAugustoRodrigues** [comment]
Hi.

You're right that using templates can offer a more practical approach to managing content than relying solely on JavaScript. While I initially envisioned using JavaScript for dynamic updates and keeping the visual layer somewhat separate, I'm open to the idea of integrating a template system.

I'll keep this issue open for further discussions. Please feel free to share any specific ideas or preferences you have regarding template engines and their integration.

**Comment by FabioAugustoRodrigues** [comment]
https://github.com/FabioAugustoRodrigues/iMono/pull/12
