### ISSUE TITLE
Cache?

### ISSUE THREAD

**Issue by carlosdaniel26** [FabioAugustoRodrigues/iMono#3]
Maybe a little less formal than my previous issues.

Well, I'm not sure what scale iMono projects are intended for, but adding a caching system, even if not for using a database like Redis, and using it in memory or in a file can be beneficial for the system's performance.

**Comment by FabioAugustoRodrigues** [comment]
Well, the initial idea of iMono is to be a framework with a simple structure but versatile enough to serve various purposes, always tailoring to the logic of the developer creating it. Therefore, adding a caching system would be ideal, especially for scenarios where data processing plays a significant role.

That being said, I'll explore options to integrate caching systems into iMono. The plan includes choosing a simple caching mechanism, configuring it via the ```.env``` file for user customization, implementing a ```CacheManager``` class within the ```/app``` directory, and integrating it into controllers or models where caching can enhance performance.

What do you think?

**Comment by carlosdaniel26** [comment]
Great idea, maybe i can help about it in some details.

**Comment by FabioAugustoRodrigues** [comment]
Great.

As I said previously, I believe that adding a class that serves as an abstraction for a cache manager would be a good option and ends up following the iMono pattern. So I thought something like this:
```app/cache/CacheManager.php:```
```php

<?php

class CacheManager
{
    public static function get($key)
    { }

    public static function put($key, $value, $minutes)
    { }
}
```

but I've never worked with caching before, so it would take me a while to implement something like this in the project, so I would appreciate any contributions.

**Comment by carlosdaniel26** [comment]
Looks great, i made some projects with caching but also never made a caching systems before, so im excited to start to implement it.

**Comment by carlosdaniel26** [comment]
Well, I've created a simplified version, but I'm confused about how it will persist in memory since we don't have a constant PHP instance in the framework like other frameworks. So, how can the class always exist?

app/cache/Cache.php


``` php
<?php

namespace app\cache;

class Cache
{
	private $cache = [];

	public function set($key, $value, $seconds = 300)
	{
		$experation_time = time() = $experation_time;
		$this->cache[$key] = ['value' => $value, 'experation' => $experation_time];
	}

	public function has($key) {
        return isset($this->cache[$key]) && $this->cache[$key]['expiration'] > time();
    }

	public function get($key)
	{
		if (has($key))
		{
			return $this->cache[$key]['value'];
		}
		else // if its experated
		{
			unset($this->cache[$key]);
            return null;
		}
	}

	public function remove($key) {
        unset($this->cache[$key]);
    }

    public function clearExpired() {
        foreach ($this->cache as $key => $item) {
            if ($item['expiration'] <= time()) {
                unset($this->cache[$key]);
            }
        }
    }

    public function clearAll() {
        foreach ($this->cache as $key => $item) {
            unset($this->cache[$key]);
        }
    }
}
```

**Comment by FabioAugustoRodrigues** [comment]
This is a great approach, but I think we need to make Cache system more versatile.
In your example, the class only has array caching, right? 

I believe that a great option is to provide other types, what do you think?
The cache type will be configured in .env file

Initially, we can just use array and file driver, and Cache class will take care of it.
When the system starts working well, we implement others like redis.

So, the implementation could be like this:

- CacheInterface.php
  This interface defines the methods that should be used
```php
<?php

namespace app\cache;

interface CacheInterface
{
    public static function getInstance();

    public function set($key, $value, $seconds = 300);
    public function has($key);
    public function get($key);
    public function remove($key);
    public function clearExpired();
    public function clearAll();
}
```
<br><br>
- CacheArray.php
This class handles caching in Array.
This class must implement an interface to have the correct methods. Every time a new cache method is created within the system, a new class will be created, for example: CacheFile.
```php
<?php

namespace app\cache;

class CacheArray implements CacheInterface
{
    private static $instance;
    private $cache = [];

    public static function getInstance()
    {
        if (!isset(self::$instance)) {
            self::$instance = new CacheArray();
        }

        return self::$instance;
    }

    public function set($key, $value, $seconds = 300)
    {
        $expiration_time = time() + $seconds;
        $this->cache[$key] = ["value" => $value, "expiration" => $expiration_time];
    }

    public function has($key)
    {
        return isset($this->cache[$key]) && $this->cache[$key]["expiration"] > time();
    }

    public function get($key)
    {
        if ($this->has($key)) {
            return $this->cache[$key]["value"];
        }

        unset($this->cache[$key]);
        return null;
    }

    public function remove($key)
    {
        unset($this->cache[$key]);
    }

    public function clearExpired()
    {
        foreach ($this->cache as $key => $item) {
            if ($item["expiration"] <= time()) {
                unset($this->cache[$key]);
            }
        }
    }

    public function clearAll()
    {
        foreach ($this->cache as $key => $item) {
            unset($this->cache[$key]);
        }
    }
}
```
<br><br>
- CacheFacade.php
This class will only deal with the creation of instances of the Cache class within the system
```php
<?php

namespace app\cache;

class CacheFacade
{
    private static $instance;
    private static $cacheType = 'array';

    public static function setCacheType($cacheType)
    {
        self::$cacheType = $cacheType;
    }

    public static function getInstance()
    {
        if (!isset(self::$instance)) {
            self::$instance = self::createInstance();
        }

        return self::$instance;
    }

    private static function createInstance()
    {
        switch (strtolower(self::$cacheType)) {
            case 'array':
                return CacheArray::getInstance();
        }
    }
}
```




Now, regarding the question of how we are going to instantiate, it is simple:
First we must inform the driver in the ``` .env``` file:
```
...
CACHE_DRIVER=array
```


then, we go to the config/source.php file (in this file we configure all the system constants) and initialize Facade:
```php
...
CacheFacade::setCacheType($_ENV['DB_DRIVER']);
CacheFacade::getInstance()->set("test", "test");
```


After that, in the controller, you can use the cache:
```php
class ExampleController extends ControllerAbstract
{

    public function __construct(
    ) {
    }

    public function getCurrentDateTime() {
        CacheFacade::getInstance()->get("test");

        return $this->respondsWithData(
            [
                "data" => [
                    "current_date_time" => date('Y-m-d H:i:s')
                ],
                "message" => ""
            ],
            200
        );
    }
}
```


<br><br><br><br><br>

What do you think of this approach?

**Comment by carlosdaniel26** [comment]
Pretty good, can you commit this? Im excited to code the redis implementation

**Comment by FabioAugustoRodrigues** [comment]
the commit is here: 
https://github.com/FabioAugustoRodrigues/iMono/commit/679c6946dfbbdbb5623ea3de013b4a965c6c9db9
