### ISSUE TITLE
Where initialize the framework?

### ISSUE THREAD

**Issue by carlosdaniel26** [FabioAugustoRodrigues/iMono#4]
Im interessed about the templates in the framework so i was going to do some experiments, but i was confused about where to start the application,  can you give me some instructions?

**Comment by FabioAugustoRodrigues** [comment]
Follow these steps:

- Install dependencies:
```
composer install
```

- Ensure that your project is hosted on a web server that supports .htaccess files. 

- Access the project: Open the web browser and navigate to your local server or the configured domain. The link to example page is in /the-framework/, that was configured in .htaccess file:
```
RewriteRule ^the-framework/(.*)$ app/views/index.html?url=$1 [NC,L]
```
<br><br><br>
Thanks for the issue, I will put these details in the project doc.

**Comment by carlosdaniel26** [comment]
Thanks, i just needed install xampp instead of just use php -S
