### ISSUE TITLE
[Question] RewriteRule in .htacess vs php router

### ISSUE THREAD

**Issue by carlosdaniel26** [FabioAugustoRodrigues/iMono#6]
Thinking about the templates systems a interessant question came to my mind, in the current framework version, the user go directly to the .html page, and inside the page is made the request to the data.

But, to create a template system i think may be need remade this flow, and must need create a intermediary part to first get the data and after go to the view.

In conclusion, a router system can be need to implement the template system.

Disagreements? Sugestions about how it can be made if its necessary?

**Comment by carlosdaniel26** [comment]
There are many possibilities for how to implement the template system in my head, so I would love suggestions and discussions on the subject

**Comment by FabioAugustoRodrigues** [comment]
issue solved here: https://github.com/FabioAugustoRodrigues/iMono/pull/7
